# Generated by Django 5.0.2 on 2024-03-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_alter_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_signified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomApp.product'),
            preserve_default=False,
        ),
    ]
