# Generated by Django 5.0.2 on 2024-03-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_alter_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_add1',
            field=models.ImageField(blank=True, null=True, upload_to='./product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_add2',
            field=models.ImageField(blank=True, null=True, upload_to='./product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_add3',
            field=models.ImageField(blank=True, null=True, upload_to='./product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_add4',
            field=models.ImageField(blank=True, null=True, upload_to='./product_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./product_pic/'),
        ),
    ]
