# Generated by Django 5.0.2 on 2024-03-02 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(0.0)])),
                ('photo', models.ImageField(upload_to='./product_pic/')),
                ('state', models.CharField(choices=[('pendinge', 'pending'), ('shipping', 'shipping'), ('complete', 'complete')], max_length=20)),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(0.0), django.core.validators.MinValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('info_livraison', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='./profile_pic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
