# Generated by Django 5.0.2 on 2024-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0006_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('shipping', 'shipping'), ('complete', 'complete')], max_length=20),
        ),
    ]
