# Generated by Django 5.0.2 on 2024-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0011_alter_cart_products_alter_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='ecomApp.product'),
        ),
    ]
