# Generated by Django 5.0.2 on 2024-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0012_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_stripe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
