# Generated by Django 5.0.2 on 2024-03-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_cart_order_review_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_pic/'),
        ),
    ]
