# Generated by Django 5.0.2 on 2024-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0014_alter_client_photo_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('shipping', 'shipping'), ('complete', 'complete')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
